# ===========================
# Datasource Configuration
# ===========================
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.show-sql=false

# ===========================
# JWT Configuration
# ===========================
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# ===========================
# RabbitMQ (Production Server)
# ===========================
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST}

# ===========================
# Logging Configuration
# ===========================
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

#============================
# Disable OpenAPI Docs
#============================
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false