# ===========================
# Datasource Configuration
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/eventhive_db
spring.datasource.username=postgres
spring.datasource.password=naveen2007
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.show-sql=true

# ===========================
# JWT Configuration
# ===========================
jwt.secret=QA7zupEZVIya2JsJCJU/jEtbj6MPGleOZHIxKZU7iL4=
jwt.expiration-ms=86400000

# ===========================
# RabbitMQ
# ===========================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=publisher
spring.rabbitmq.password=pub@2020
spring.rabbitmq.virtual-host=/

# ===========================
# Logging Configuration
# ===========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===========================
# Spring Devtools config
# ===========================
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true