# ===========================
# Application Configuration
# ===========================
spring.application.name=EventHive

# ===========================
# Server Configuration
# ===========================
server.port=8080

# ===========================
# JPA / Hibernate Configuration (common parts)
# ===========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# Liquibase Configuration
# ===========================
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# ===========================
# Dev tools Configuration
# ===========================
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=1s
spring.devtools.restart.quiet-period=400ms

# ===========================
# Performance / DX
# ===========================
spring.jpa.open-in-view=false
spring.main.lazy-initialization=true
spring.output.ansi.enabled=always
