package com.thehiveproject.event.domain.booking

import com.thehiveproject.event.domain.event.Event
import com.thehiveproject.event.infrastructure.persistence.event.TicketTierEntity // Or a Domain equivalent if you have one
import java.math.BigDecimal
import java.time.Instant
import java.time.ZoneId
import java.util.*

class Booking(
    val id: Long? = null,
    val bookingReference: String,
    val userId: Long,
    val eventId: Long,
    val ticketTierId: Long,
    val ticketTierName: String,
    val eventTitle: String,
    val eventDescription: String,
    val eventDate: Instant,
    val eventEndDate: Instant,
    val eventLocation: String,
    val ticketsCount: Int,
    val totalPrice: BigDecimal,
    val status: BookingStatus,
    val createdBy: Long,
    val updatedBy: Long,
    val createdAt: Instant,
    val updatedAt: Instant,
    val isActive: Boolean,
    val isDeleted: Boolean
){
    companion object {
        fun create(
            userId: Long,
            event: Event,
            tier: TicketTierEntity,
            ticketsCount: Int,
            createdBy: Long
        ): Booking {
            return Booking(
                // booking reference is generated by the system
                bookingReference = UUID.randomUUID().toString(),

                // user id is the id of the user who created the booking
                userId = userId,

                // event id is the id of the event
                eventId = event.id!!,

                // ticket tier id and name are the id and name of the ticket tier
                ticketTierId = tier.id!!,
                ticketTierName = tier.name,

                // event title, description, date, end date, location are the title, description, start date, end date, location of the event
                eventTitle = event.title,
                eventDescription = event.description,
                eventDate = event.startDate.atZone(ZoneId.systemDefault()).toInstant(),
                eventEndDate = event.endDate.atZone(ZoneId.systemDefault()).toInstant(),
                eventLocation = event.location,

                // tickets count is the number of tickets booked
                ticketsCount = ticketsCount,
                totalPrice = tier.price * BigDecimal(ticketsCount),

                // booking status is the status of the booking
                status = BookingStatus.PENDING_PAYMENT,

                //auditable fields
                createdBy = createdBy,
                updatedBy = createdBy,
                createdAt = Instant.now(),
                updatedAt = Instant.now(),
                isActive = true,
                isDeleted = false
            )
        }
    }
}